FROM public.ecr.aws/docker/library/rust@sha256:fb328f0f58becb23ba1719940a2c94ece8b0b48afa837d05b79ef64bc1e18f6e
ENV DEBIAN_FRONTEND=noninteractive
RUN rustup target add wasm32-unknown-unknown
WORKDIR /work
COPY . .
RUN cd packages/dialects/pkd-dialect-true && cargo build --target wasm32-unknown-unknown --release
