FROM public.ecr.aws/docker/library/rust@sha256:70aebe351faa35667ef36508deb19fe234ff03d67cfe102f095d920a53d0622c
RUN rustup target add wasm32-unknown-unknown
WORKDIR /work
COPY . .
RUN cd packages/dialects/pkd-dialect-true && cargo build --target wasm32-unknown-unknown --release
