/* ========================================================================
 * Project: Pharos Kitchen Design (Project Prism)
 * Component: Infrastructure / DNS
 * File: infra/cloud/dns_auth.tf
 * Author: Richard D. (https://github.com/iamrichardd)
 * License: FSL-1.1
 * Purpose: Authoritative Email Deliverability Records (SPF, DKIM, DMARC).
 * Traceability: Issue #205, ADR-0050
 * ======================================================================== */

# --- SPF (Sender Policy Framework) ---
# Authorizes Cloudflare Email Routing to send on behalf of the domain.
resource "cloudflare_record" "spf" {
  zone_id = var.cloudflare_zone_id
  name    = "@"
  value   = "v=spf1 include:_spf.mx.cloudflare.net ~all"
  type    = "TXT"
  ttl     = 3600
}

# --- DKIM (DomainKeys Identified Mail) ---
# These are placeholder values. In a real environment, these would be 
# generated by the Cloudflare Dashboard / API and mapped here.
resource "cloudflare_record" "dkim" {
  zone_id = var.cloudflare_zone_id
  name    = "cloudflare._domainkey"
  value   = "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD..."
  type    = "TXT"
  ttl     = 3600
}

# --- DMARC (Domain-based Message Authentication) ---
# Instructs recipient servers to quarantine emails that fail SPF/DKIM.
resource "cloudflare_record" "dmarc" {
  zone_id = var.cloudflare_zone_id
  name    = "_dmarc"
  value   = "v=DMARC1; p=quarantine; rua=mailto:admin@iamrichardd.com"
  type    = "TXT"
  ttl     = 3600
}
